// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HandShake struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Done                 bool     `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandShake) Reset()         { *m = HandShake{} }
func (m *HandShake) String() string { return proto.CompactTextString(m) }
func (*HandShake) ProtoMessage()    {}
func (*HandShake) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_5cbe0f978dee8010, []int{0}
}
func (m *HandShake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandShake.Unmarshal(m, b)
}
func (m *HandShake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandShake.Marshal(b, m, deterministic)
}
func (dst *HandShake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandShake.Merge(dst, src)
}
func (m *HandShake) XXX_Size() int {
	return xxx_messageInfo_HandShake.Size(m)
}
func (m *HandShake) XXX_DiscardUnknown() {
	xxx_messageInfo_HandShake.DiscardUnknown(m)
}

var xxx_messageInfo_HandShake proto.InternalMessageInfo

func (m *HandShake) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *HandShake) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func init() {
	proto.RegisterType((*HandShake)(nil), "protos.HandShake")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_5cbe0f978dee8010) }

var fileDescriptor_message_5cbe0f978dee8010 = []byte{
	// 92 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0xc6,
	0x5c, 0x9c, 0x1e, 0x89, 0x79, 0x29, 0xc1, 0x19, 0x89, 0xd9, 0xa9, 0x42, 0x42, 0x5c, 0x2c, 0x25,
	0xa9, 0x15, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0x36, 0x48, 0x2c, 0x25, 0x3f,
	0x2f, 0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x23, 0x08, 0xcc, 0x4e, 0x82, 0x68, 0x36, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xdc, 0x0f, 0x05, 0xa9, 0x54, 0x00, 0x00, 0x00,
}
